version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Eslint Front end
          command: yarn test:eslint:frontend
      - run:
          name: Eslint Api
          command: yarn test:eslint:api
      - run:
          name: Unit Tests
          command: yarn test

workflows:
  version: 2
  testAndDeployDev:
    jobs:
      - test
